const PDFDocument = require("pdfkit");

const generateInvoice = (sale, company, res) => {

    const doc = new PDFDocument({
        size: "A4",
        margin: 50
    });

    res.setHeader(
        "Content-Type",
        "application/pdf"
    );

    res.setHeader(
        "Content-Disposition",
        `attachment; filename=${sale.invoiceNumber}.pdf`
    );

    doc.pipe(res);

    // ===========================
    // Company
    // ===========================

    doc
        .fontSize(22)
        .text(company.companyName, {
            align: "center"
        });

    doc
        .fontSize(10)
        .text(company.address, {
            align: "center"
        });

    doc.text(
        `Phone : ${company.phone}`,
        {
            align: "center"
        }
    );

    doc.text(
        `GST : ${company.gstNumber}`,
        {
            align: "center"
        }
    );

    doc.moveDown();

    doc
        .fontSize(18)
        .text("TAX INVOICE", {
            align: "center"
        });

    doc.moveDown();

    // ===========================
    // Invoice Details
    // ===========================

    doc.fontSize(12);

    doc.text(`Invoice No : ${sale.invoiceNumber}`);

    doc.text(`Invoice Date : ${new Date(sale.createdAt).toLocaleDateString()}`);

    doc.text(`Customer : ${sale.customerName}`);

    doc.text(`Phone : ${sale.customerPhone}`);

    doc.text(`Payment : ${sale.paymentMethod}`);

    doc.moveDown();

    // ===========================
    // Product
    // ===========================

    doc.text("-----------------------------------------------");

    doc.moveDown();

    doc.text(`Medicine : ${sale.product.productName}`);

    doc.text(`Quantity : ${sale.quantity}`);

    doc.text(`Price : ₹${sale.sellingPrice}`);

    doc.text(`Total : ₹${sale.totalAmount}`);

    doc.moveDown();

    doc.text("-----------------------------------------------");

    doc.moveDown();

    doc
        .fontSize(16)
        .text(
            `Grand Total : ₹${sale.totalAmount}`,
            {
                align: "right"
            }
        );

    doc.moveDown();

    doc.moveDown();

    doc.text("Authorized Signature", {
        align: "right"
    });

    doc.moveDown();

    doc.fontSize(10);

    doc.text(
        "Generated by Gloss Pharma ERP",
        {
            align: "center"
        }
    );

    doc.end();

};

module.exports = {
    generateInvoice
};